### ISSUE TITLE
ociregistry/ociclient: implement auth

### ISSUE THREAD

**Issue by rogpeppe** [cue-labs/oci#10]
Currently `ociclient` knows nothing about authentication or authorization, but it should support
the most common standard auth methods, hopefully without incurring large dependency requirements.

[This package](https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/remote/transport) is likely a good place to start.

**Comment by tianon** [comment]
Now that `cuelabs.dev/go/oci/ociregistry/ociauth` is a thing (and `ociclient` knows how to use it), this is fixed, right? :eyes:

**Comment by mvdan** [comment]
I believe so, this issue is quite old and we've supported (and used) Docker-style auth with OCI requests for some months now.

For example, see our use in the cmd/cue tool here: https://github.com/cue-lang/cue/blob/64a117c07a084f82970596f3ac67023087952f4f/cmd/cue/cmd/registry.go#L44-L82

What matters for the "standard" Docker-style auth is `ociauth.Load` and `ociauth.NewStdAuthorizer`.
